import { defineConfig } from 'vitepress'

// https://vitepress.vuejs.org/config/app-configs
export default defineConfig({    // 站点级选项
  title: 'Kirara',
  description: '一个让你和电报好友保持持续联系的申必魔法工具',

  themeConfig: {
    footer: {
      message: 'Kirara was released under GPL3 License.',
      copyright: 'This app\'s icon is AI-generated by <a href="https://github.com/baiyuanneko" target="_blank">baiyuanneko</a>. Made with love by <a href="https://chinet.work/" target="_blank">chi Network Contributors</a>©2022-2024'
    }
    // 主题级选项
  }
})
